[functions]
  # Bundle your modpack files so the function can read them at runtime
  included_files = ["modpacks/**/**"]

# Map /:slug and /:slug/* to the function
[[redirects]]
  from = "/:slug"
  to   = "/.netlify/functions/packwiz-serve/:slug"
  status = 200

[[redirects]]
  from = "/:slug/*"
  to   = "/.netlify/functions/packwiz-serve/:slug/*"
  status = 200

[[redirects]]
  from = "/"
  to = "https://pnfx.dev"
  status = 301
  force = true

[[headers]]
for = "/"
[headers.values]
X-Robots-Tag = "noindex, nofollow"